### ISSUE TITLE
Blueprints for Spreadsheet Gateway require version 1.0.0 but actual is 1.6.0

### ISSUE THREAD

**Issue by jensherder** [SuperFlyTV/sofie-demo-blueprints#6]
We do not manage to get Sofie Automation with the Spreadsheet Gateway running. When we start the Sofie Core with meteor, the system shows the version 1.6.0, but the blueprints complain that 1.0.0 is required. Changing the requirement for one blueprint creates a different error. Maybe the blueprints on git are not up-to-date. Here the error messages in the rundown section:
System Status: FAIL / BAD
Status Messages:
check blueprintCompability_8zMYtXf5cRBd4oCz3: Core - TSR library version: Version mismatch: blueprint.TSRVersion version: "3.2.0" does not satisfy expected version range of core.timeline-state-resolver-types: ">=3.18.0 <4.0.0" (Blueprint has to be updated)
check blueprintCompability_FtTn8trdf8miJNNoJ: Core version: Version mismatch: blueprint.minimumCoreVersion version: "1.6.0" does not satisfy expected version of core system: "1.0.0" (Blueprint does not support this version of core)
check blueprintCompability_TdFdS3bufuPRpJp6E: Core version: Version mismatch: blueprint.minimumCoreVersion version: "1.6.0" does not satisfy expected version of core system: "1.0.0" (Blueprint does not support this version of core)
Playout gateway: MediaScanner not connected

Any help would be appreciated.

Kind regards,

Jens Herder

**Comment by baltedewit** [comment]
We currently do not actively maintain these blueprints so they are based on an older version of Sofie.

Blueprints integrate closely with the version of server-core, and the timeline-state-resolver and blueprints-integration library. The master branch for these blueprints integrates with Core version 1.0.0, TSR 3.8.3 and integration 0.24.1.

If you change the minimum version of core in the blueprints you will have to upgrade the TSR and integration as well.

**Comment by alvancamp** [comment]
Closing as out-of-date. The current master branch of these blueprints is compatible with Sofie Core R37, and once #52 is merged, master will be compatible with R46.
